### ISSUE TITLE
Fails to Build Due to Cargo Patch

### ISSUE THREAD

**Issue by rauljordan** [ralexstokes/mev-rs#91]
Hi @ralexstokes, having some difficulties building due to the patch present in Cargo.toml it seems.

## System

Ubuntu 22.04.2 LTS, x86
```
cargo --version
cargo 1.68.0-nightly (cc0a32087 2022-12-14)
```
The error also happens when using the stable toolchain

## Error
```
$ cargo build
    Updating git repository `https://github.com/ralexstokes//ssz-rs`
warning: spurious network error (2 tries remaining): remote error: 
  ralexstokes//ssz-rs is not a valid repository name
  Visit https://support.github.com/ for help; class=Net (12)
warning: spurious network error (1 tries remaining): remote error: 
  ralexstokes//ssz-rs is not a valid repository name
  Visit https://support.github.com/ for help; class=Net (12)
error: failed to load source for dependency `ssz-rs`

Caused by:
  Unable to update https://github.com/ralexstokes//ssz-rs?rev=45ff6f1

Caused by:
  failed to fetch into: /home/zodiark/.cargo/git/db/ssz-rs-50b4fc47aaa300b4

Caused by:
  failed to authenticate when downloading repository: ssh://git@github.com/ralexstokes//ssz-rs

  * attempted ssh-agent authentication, but no usernames succeeded: `git`

  if the git CLI succeeds then `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  remote error: 
    ralexstokes//ssz-rs is not a valid repository name
    Visit https://support.github.com/ for help; class=Net (12)
```

**Comment by michaelsproul** [comment]
+1 to cleaning up the `patch` situation. The current approach feels really hacky and requires all downstream dependencies of `mev-rs` to replicate the URL patch. E.g. we have this in Lighthouse:

https://github.com/sigp/lighthouse/blob/693886b94176faa4cb450f024696cb69cda2fe58/Cargo.toml#L107-L112

I tried to get rid of that just now, but I couldn't because `mev-rs` doesn't pin commit hashes in the Cargo.toml:

https://github.com/ralexstokes/mev-rs/blob/cb34b70bf98e5aac3a1a00fe20412f4c6aea2edc/mev-rs/Cargo.toml#L29-L31

I guess this approach was taken so that the commit hash could be pinned _once_ for the entire workspace? If that's the case I think the trade-off isn't worth it: a significant UX burden for dependencies to save a few lines of duplication.

**Comment by ralexstokes** [comment]
hi @rauljordan @michaelsproul sorry for the hassle here, I'm fixing this in #107
